-- Northwind Commerce RBAC roles, masking policies, row access policies, and governance tags


/*
=============================================================================
  SECURITY - RBAC Implementation
  Implements least-privilege roles for data engineering, analytics, and admin.
=============================================================================
*/

-- ============================================================================
-- CUSTOM ROLES
-- ============================================================================

CREATE ROLE IF NOT EXISTS NORTHWIND_ADMIN
    COMMENT = 'Full administrative access to Northwind databases';

CREATE ROLE IF NOT EXISTS NORTHWIND_ENGINEER
    COMMENT = 'Read/write access for data engineering pipelines';

CREATE ROLE IF NOT EXISTS NORTHWIND_ANALYST
    COMMENT = 'Read-only access to warehouse and analytics views';

CREATE ROLE IF NOT EXISTS NORTHWIND_LOADER
    COMMENT = 'Service role for automated data loading (Snowpipe, Tasks)';

-- ============================================================================
-- ROLE HIERARCHY
-- ============================================================================

GRANT ROLE NORTHWIND_LOADER TO ROLE NORTHWIND_ENGINEER;
GRANT ROLE NORTHWIND_ANALYST TO ROLE NORTHWIND_ENGINEER;
GRANT ROLE NORTHWIND_ENGINEER TO ROLE NORTHWIND_ADMIN;
GRANT ROLE NORTHWIND_ADMIN TO ROLE SYSADMIN;

-- ============================================================================
-- WAREHOUSE GRANTS
-- ============================================================================

GRANT USAGE ON WAREHOUSE NORTHWIND_LOAD_WH TO ROLE NORTHWIND_LOADER;
GRANT USAGE ON WAREHOUSE NORTHWIND_LOAD_WH TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON WAREHOUSE NORTHWIND_TRANSFORM_WH TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON WAREHOUSE NORTHWIND_ANALYTICS_WH TO ROLE NORTHWIND_ANALYST;
GRANT ALL ON WAREHOUSE NORTHWIND_LOAD_WH TO ROLE NORTHWIND_ADMIN;
GRANT ALL ON WAREHOUSE NORTHWIND_TRANSFORM_WH TO ROLE NORTHWIND_ADMIN;
GRANT ALL ON WAREHOUSE NORTHWIND_ANALYTICS_WH TO ROLE NORTHWIND_ADMIN;

-- ============================================================================
-- DATABASE GRANTS
-- ============================================================================

-- RAW database
GRANT USAGE ON DATABASE NORTHWIND_RAW TO ROLE NORTHWIND_LOADER;
GRANT USAGE ON DATABASE NORTHWIND_RAW TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_RAW TO ROLE NORTHWIND_LOADER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_RAW TO ROLE NORTHWIND_ENGINEER;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA NORTHWIND_RAW.ECOMMERCE TO ROLE NORTHWIND_LOADER;
GRANT SELECT ON ALL TABLES IN SCHEMA NORTHWIND_RAW.ECOMMERCE TO ROLE NORTHWIND_ENGINEER;
GRANT READ, WRITE ON STAGE NORTHWIND_RAW.STAGING_AREA.ECOMMERCE_STAGE TO ROLE NORTHWIND_LOADER;
GRANT READ ON STAGE NORTHWIND_RAW.STAGING_AREA.ECOMMERCE_STAGE TO ROLE NORTHWIND_ENGINEER;

-- STAGING database
GRANT USAGE ON DATABASE NORTHWIND_STAGING TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_STAGING TO ROLE NORTHWIND_ENGINEER;
GRANT ALL ON ALL TABLES IN SCHEMA NORTHWIND_STAGING.ECOMMERCE TO ROLE NORTHWIND_ENGINEER;

-- DW database
GRANT USAGE ON DATABASE NORTHWIND_DW TO ROLE NORTHWIND_ANALYST;
GRANT USAGE ON DATABASE NORTHWIND_DW TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_DW TO ROLE NORTHWIND_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_DW TO ROLE NORTHWIND_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE NORTHWIND_DW TO ROLE NORTHWIND_ANALYST;
GRANT ALL ON ALL TABLES IN DATABASE NORTHWIND_DW TO ROLE NORTHWIND_ENGINEER;

-- MONITORING database
GRANT USAGE ON DATABASE NORTHWIND_MONITORING TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_MONITORING TO ROLE NORTHWIND_ENGINEER;
GRANT ALL ON ALL TABLES IN DATABASE NORTHWIND_MONITORING TO ROLE NORTHWIND_ENGINEER;
GRANT USAGE ON DATABASE NORTHWIND_MONITORING TO ROLE NORTHWIND_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHWIND_MONITORING TO ROLE NORTHWIND_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE NORTHWIND_MONITORING TO ROLE NORTHWIND_ANALYST;

-- ============================================================================
-- MASKING POLICIES
-- ============================================================================

CREATE OR REPLACE MASKING POLICY NORTHWIND_DW.DIMENSIONS.MASK_EMAIL AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('NORTHWIND_ADMIN', 'NORTHWIND_ENGINEER', 'ACCOUNTADMIN')
            THEN val
        ELSE REGEXP_REPLACE(val, '.+@', '***@')
    END
COMMENT = 'Masks email addresses for non-privileged roles';

CREATE OR REPLACE MASKING POLICY NORTHWIND_DW.DIMENSIONS.MASK_PHONE AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('NORTHWIND_ADMIN', 'NORTHWIND_ENGINEER', 'ACCOUNTADMIN')
            THEN val
        ELSE '***-***-' || RIGHT(val, 4)
    END
COMMENT = 'Masks phone numbers, showing only last 4 digits';

CREATE OR REPLACE MASKING POLICY NORTHWIND_DW.DIMENSIONS.MASK_SALARY AS
    (val NUMBER) RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('NORTHWIND_ADMIN', 'ACCOUNTADMIN')
            THEN val
        ELSE NULL
    END
COMMENT = 'Hides salary data from non-admin roles';

-- ============================================================================
-- ROW ACCESS POLICY
-- ============================================================================

CREATE OR REPLACE ROW ACCESS POLICY NORTHWIND_DW.DIMENSIONS.RAP_SEGMENT_ACCESS AS
    (segment VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('NORTHWIND_ADMIN', 'NORTHWIND_ENGINEER', 'ACCOUNTADMIN')
            THEN TRUE
        WHEN CURRENT_ROLE() = 'NORTHWIND_ANALYST' AND segment IN ('Consumer', 'Corporate')
            THEN TRUE
        ELSE FALSE
    END
COMMENT = 'Restricts analyst access to Consumer and Corporate segments only';

-- ============================================================================
-- TAGS
-- ============================================================================

CREATE OR REPLACE TAG NORTHWIND_DW.DIMENSIONS.PII_LEVEL
    ALLOWED_VALUES 'HIGH', 'MEDIUM', 'LOW'
    COMMENT = 'Classifies columns by PII sensitivity level';

CREATE OR REPLACE TAG NORTHWIND_DW.DIMENSIONS.DATA_DOMAIN
    ALLOWED_VALUES 'CUSTOMER', 'ORDER', 'PRODUCT', 'FINANCIAL', 'EMPLOYEE', 'LOGISTICS'
    COMMENT = 'Business domain classification for data governance';
