-- Northwind Commerce: Scheduled tasks for incremental data processing


/*
=============================================================================
  TASKS - Incremental Processing Pipeline
  Merges stream data into staging tables on a schedule.
=============================================================================
*/

USE DATABASE NORTHWIND_STAGING;
USE SCHEMA ECOMMERCE;

-- ============================================================================
-- STAGING TABLES (targets for MERGE)
-- ============================================================================

CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    FULL_NAME           VARCHAR(201),
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(50),
    DATE_OF_BIRTH       DATE,
    AGE                 NUMBER(3,0),
    GENDER              VARCHAR(20),
    ADDRESS_LINE1       VARCHAR(255),
    CITY                VARCHAR(100),
    STATE               VARCHAR(50),
    POSTAL_CODE         VARCHAR(20),
    COUNTRY             VARCHAR(100),
    CUSTOMER_SEGMENT    VARCHAR(50),
    REGISTRATION_DATE   TIMESTAMP_NTZ,
    IS_ACTIVE           BOOLEAN,
    LOYALTY_TIER        VARCHAR(20),
    _LOADED_AT          TIMESTAMP_NTZ,
    _UPDATED_AT         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STG_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
)
COMMENT = 'Cleansed customer data with derived fields';

CREATE OR REPLACE TABLE STG_ORDERS (
    ORDER_ID            VARCHAR(50)     NOT NULL,
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    ORDER_DATE          TIMESTAMP_NTZ,
    ORDER_DATE_KEY      NUMBER(8,0),
    REQUIRED_DATE       DATE,
    SHIPPED_DATE        TIMESTAMP_NTZ,
    ORDER_STATUS        VARCHAR(30),
    SHIPPING_METHOD     VARCHAR(50),
    SHIPPING_COST       NUMBER(10,2),
    SUBTOTAL            NUMBER(12,2),
    TAX_AMOUNT          NUMBER(10,2),
    DISCOUNT_AMOUNT     NUMBER(10,2),
    TOTAL_AMOUNT        NUMBER(12,2),
    WAREHOUSE_ID        VARCHAR(50),
    EMPLOYEE_ID         VARCHAR(50),
    PROMOTION_ID        VARCHAR(50),
    _LOADED_AT          TIMESTAMP_NTZ,
    _UPDATED_AT         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STG_ORDERS PRIMARY KEY (ORDER_ID)
)
COMMENT = 'Cleansed orders with date key for star schema join';

CREATE OR REPLACE TABLE STG_PAYMENTS (
    PAYMENT_ID          VARCHAR(50)     NOT NULL,
    ORDER_ID            VARCHAR(50)     NOT NULL,
    PAYMENT_DATE        TIMESTAMP_NTZ,
    PAYMENT_METHOD      VARCHAR(50),
    AMOUNT              NUMBER(12,2),
    CURRENCY            VARCHAR(10),
    PAYMENT_STATUS      VARCHAR(30),
    _LOADED_AT          TIMESTAMP_NTZ,
    _UPDATED_AT         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STG_PAYMENTS PRIMARY KEY (PAYMENT_ID)
)
COMMENT = 'Cleansed payment transactions';

-- ============================================================================
-- MERGE TASKS
-- ============================================================================

CREATE OR REPLACE TASK NORTHWIND_RAW.ECOMMERCE.TASK_MERGE_CUSTOMERS
    WAREHOUSE = NORTHWIND_LOAD_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('NORTHWIND_RAW.ECOMMERCE.STM_RAW_CUSTOMERS')
AS
MERGE INTO NORTHWIND_STAGING.ECOMMERCE.STG_CUSTOMERS AS tgt
USING (
    SELECT
        CUSTOMER_ID,
        TRIM(FIRST_NAME)                            AS FIRST_NAME,
        TRIM(LAST_NAME)                             AS LAST_NAME,
        TRIM(FIRST_NAME) || ' ' || TRIM(LAST_NAME) AS FULL_NAME,
        LOWER(TRIM(EMAIL))                          AS EMAIL,
        PHONE,
        DATE_OF_BIRTH,
        DATEDIFF(YEAR, DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
        GENDER,
        ADDRESS_LINE1,
        CITY,
        UPPER(STATE)                                AS STATE,
        POSTAL_CODE,
        COUNTRY,
        CUSTOMER_SEGMENT,
        REGISTRATION_DATE,
        IS_ACTIVE,
        LOYALTY_TIER,
        _LOADED_AT
    FROM NORTHWIND_RAW.ECOMMERCE.STM_RAW_CUSTOMERS
    WHERE METADATA$ACTION = 'INSERT'
) AS src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.FIRST_NAME = src.FIRST_NAME,
    tgt.LAST_NAME = src.LAST_NAME,
    tgt.FULL_NAME = src.FULL_NAME,
    tgt.EMAIL = src.EMAIL,
    tgt.PHONE = src.PHONE,
    tgt.CITY = src.CITY,
    tgt.STATE = src.STATE,
    tgt.POSTAL_CODE = src.POSTAL_CODE,
    tgt.CUSTOMER_SEGMENT = src.CUSTOMER_SEGMENT,
    tgt.IS_ACTIVE = src.IS_ACTIVE,
    tgt.LOYALTY_TIER = src.LOYALTY_TIER,
    tgt._UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, EMAIL, PHONE,
    DATE_OF_BIRTH, AGE, GENDER, ADDRESS_LINE1, CITY, STATE,
    POSTAL_CODE, COUNTRY, CUSTOMER_SEGMENT, REGISTRATION_DATE,
    IS_ACTIVE, LOYALTY_TIER, _LOADED_AT
) VALUES (
    src.CUSTOMER_ID, src.FIRST_NAME, src.LAST_NAME, src.FULL_NAME, src.EMAIL, src.PHONE,
    src.DATE_OF_BIRTH, src.AGE, src.GENDER, src.ADDRESS_LINE1, src.CITY, src.STATE,
    src.POSTAL_CODE, src.COUNTRY, src.CUSTOMER_SEGMENT, src.REGISTRATION_DATE,
    src.IS_ACTIVE, src.LOYALTY_TIER, src._LOADED_AT
);

CREATE OR REPLACE TASK NORTHWIND_RAW.ECOMMERCE.TASK_MERGE_ORDERS
    WAREHOUSE = NORTHWIND_LOAD_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('NORTHWIND_RAW.ECOMMERCE.STM_RAW_ORDERS')
AS
MERGE INTO NORTHWIND_STAGING.ECOMMERCE.STG_ORDERS AS tgt
USING (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_DATE,
        TO_NUMBER(TO_CHAR(ORDER_DATE, 'YYYYMMDD')) AS ORDER_DATE_KEY,
        REQUIRED_DATE,
        SHIPPED_DATE,
        ORDER_STATUS,
        SHIPPING_METHOD,
        SHIPPING_COST,
        SUBTOTAL,
        TAX_AMOUNT,
        DISCOUNT_AMOUNT,
        TOTAL_AMOUNT,
        WAREHOUSE_ID,
        EMPLOYEE_ID,
        PROMOTION_ID,
        _LOADED_AT
    FROM NORTHWIND_RAW.ECOMMERCE.STM_RAW_ORDERS
    WHERE METADATA$ACTION = 'INSERT'
) AS src
ON tgt.ORDER_ID = src.ORDER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.ORDER_STATUS = src.ORDER_STATUS,
    tgt.SHIPPED_DATE = src.SHIPPED_DATE,
    tgt._UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_DATE_KEY, REQUIRED_DATE,
    SHIPPED_DATE, ORDER_STATUS, SHIPPING_METHOD, SHIPPING_COST,
    SUBTOTAL, TAX_AMOUNT, DISCOUNT_AMOUNT, TOTAL_AMOUNT,
    WAREHOUSE_ID, EMPLOYEE_ID, PROMOTION_ID, _LOADED_AT
) VALUES (
    src.ORDER_ID, src.CUSTOMER_ID, src.ORDER_DATE, src.ORDER_DATE_KEY, src.REQUIRED_DATE,
    src.SHIPPED_DATE, src.ORDER_STATUS, src.SHIPPING_METHOD, src.SHIPPING_COST,
    src.SUBTOTAL, src.TAX_AMOUNT, src.DISCOUNT_AMOUNT, src.TOTAL_AMOUNT,
    src.WAREHOUSE_ID, src.EMPLOYEE_ID, src.PROMOTION_ID, src._LOADED_AT
);

CREATE OR REPLACE TASK NORTHWIND_RAW.ECOMMERCE.TASK_MERGE_PAYMENTS
    WAREHOUSE = NORTHWIND_LOAD_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('NORTHWIND_RAW.ECOMMERCE.STM_RAW_PAYMENTS')
AS
MERGE INTO NORTHWIND_STAGING.ECOMMERCE.STG_PAYMENTS AS tgt
USING (
    SELECT
        PAYMENT_ID,
        ORDER_ID,
        PAYMENT_DATE,
        PAYMENT_METHOD,
        AMOUNT,
        CURRENCY,
        PAYMENT_STATUS,
        _LOADED_AT
    FROM NORTHWIND_RAW.ECOMMERCE.STM_RAW_PAYMENTS
    WHERE METADATA$ACTION = 'INSERT'
) AS src
ON tgt.PAYMENT_ID = src.PAYMENT_ID
WHEN MATCHED THEN UPDATE SET
    tgt.PAYMENT_STATUS = src.PAYMENT_STATUS,
    tgt._UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PAYMENT_ID, ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD,
    AMOUNT, CURRENCY, PAYMENT_STATUS, _LOADED_AT
) VALUES (
    src.PAYMENT_ID, src.ORDER_ID, src.PAYMENT_DATE, src.PAYMENT_METHOD,
    src.AMOUNT, src.CURRENCY, src.PAYMENT_STATUS, src._LOADED_AT
);
